- name: Check if cargo is installed
  shell:
    cmd: command -v cargo
  register: cargo_exists
  ignore_errors: yes

- name: Download Installer
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: "0755"
    force: yes
  when:
    - cargo_exists is failed
  tags:
    - rust

- name: Install rust/cargo
  shell:
    cmd: /tmp/sh.rustup.rs -y
  when:
    - cargo_exists is failed
  tags:
    - rust

- name: Upload profile for rust
  copy:
    src: rust.sh
    dest: /etc/profile.d/
    owner: root
    group: root
    mode: "0644"
  when:
    - cargo_exists is failed
  tags:
    - rust

- name: Install cargo-make
  shell:
    cmd: /root/.cargo/bin/cargo install --force cargo-make
  when:
    - cargo_exists is failed
  tags:
    - rust
