- name: Download awscli
  get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscliv2.zip
  tags:
    - awscli

- name: Unarchive awscliv2.zip
  unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp/
    remote_src: yes
  tags:
    - awscli

- name: Install awscli
  shell:
    cmd: sh /tmp/aws/install
  tags:
    - awscli
